spring:
  application.name: kgp-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/got
    username: rk
    password: test123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
app:
  security:
    jwt:
      token:
        secret: 55efe25ab13568c4ce9b8c2f56b7f91adf7171cf1223fddc88833e6d1b4d150460d48843c2fd5933f8ec6bb2a327e99379e65a66214bd01cf1c7b00b4656e338
        validity: 12h
#  flyway:
#    locations: db/migration/postgres
server:
  port: 8080

weather:
  api:
    key: 1fca4767945c4ee6b33133345241807
    url: 'http://api.weatherapi.com/v1/'
