spring:
  application.name: kgp-backend
  config:
    import: classpath:application-secrets.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
#  flyway:
#    locations: db/migration/postgres
server:
  port: 8080
springdoc:
  default-consumes-media-type: "application/json"
  default-produces-media-type: "application/json"
  swagger-ui:
    operationsSorter: "method"