spring:
  application.name: kgp-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/got
    username: rk
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
#  flyway:
#    locations: db/migration/postgres
server:
  port: 8888


