# To run application: copy this to application-secrets.yml
# Set the credentials for your database and weather key.
# Weather key can be obtained on https://www.weatherapi.com/
# This should be used only for credentials and other local-only config.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: us
    password: us

app:
  security:
    jwt:
      token:
        secret: 55efe25ab13568c4ce9b8c2f56b7f91adf7171cf1223fddc88833e6d1b4d150460d48843c2fd5933f8ec6bb2a327e99379e65a66214bd01cf1c7b00b4656e338
        validity: 12h

weather:
  api:
    key: weather-key
    url: 'http://api.weatherapi.com/v1/'