### REGISTER USER 1

POST localhost:8888/got/v1/auth/register
Content-Type: application/json

{
  "login": "user1",
  "password": "password",
  "email": "user1@email.com"
}

### REGISTER USER 2

POST localhost:8888/got/v1/auth/register
Content-Type: application/json

{
  "login": "user2",
  "password": "password",
  "email": "user2@email.com"
}

### LOGIN AS USER 1

POST localhost:8888/got/v1/auth/login
Content-Type: application/json

{
"username": "user1",
"password": "password"
}

> {% client.global.set("auth-token", response.body.token); %}

### LOGIN AS ADMIN

POST localhost:8888/got/v1/auth/login
Content-Type: application/json

{
"username": "admin",
"password": "admin"
}

> {% client.global.set("auth-token", response.body.token); %}
