### REGISTER USER

POST localhost:8888/got/v1/auth/register
Content-Type: application/json

{
  "login": "user",
  "password": "password",
  "email": "user@email.com"
}

### LOGIN AS USER

POST localhost:8888/got/v1/auth/login
Content-Type: application/json

{
"username": "user",
"password": "password"
}

> {% client.global.set("auth-token", response.body.token); %}

### LOGIN AS ADMIN

POST localhost:8888/got/v1/auth/login
Content-Type: application/json

{
"username": "admin",
"password": "admin"
}

> {% client.global.set("auth-token", response.body.token); %}
