### GET ALL

GET localhost:8888/got/v1/challenges?status=g
Authorization: Bearer {{auth-token}}


### GET ALL SIMPLE

GET localhost:8888/got/v1/challenges?fields=id,name,status
Authorization: Bearer {{auth-token}}


### ADD NEW

POST localhost:8888/got/v1/challenges/add-new
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "name": "Super Hard Challenge",
  "description": "",
  "status": "ACTIVE"
}

> {% client.global.set("challenge-id", response.body.id); %}


### GET ONE

GET localhost:8888/got/v1/challenges/{{challenge-id}}
Authorization: Bearer {{auth-token}}


### ATTACH SUMMIT

POST localhost:8888/got/v1/challenges/{{challenge-id}}/attach-summit/{{summit-id}}
Authorization: Bearer {{auth-token}}
