### GOT

GET localhost:8888/got/v1/users

###

GET localhost:8888/got/v1/users/furczak

###

POST localhost:8888/got/v1/users
Content-Type: application/json

{
  "login": "furczak",
  "password": "test123",
  "email": "furczak31@gmail.com"
}

###

DELETE localhost:8888/got/v1/users/furczak