### GET ALL

GET localhost:8888/got/v1/users

### GET ONE

GET localhost:8888/got/v1/users/furczak

### NEW USER

POST localhost:8888/got/v1/users
Content-Type: application/json

{
  "login": "furczak",
  "password": "test123",
  "email": "furczak31@gmail.com"
}

### LOGIN

POST localhost:8888/got/v1/users/furczak
Content-Type: application/json

{
  "login": "furczak",
  "password": "test123"
}

### UPDATE

PUT localhost:8888/got/v1/users/furczak
Content-Type: application/json

{
  "name": "furczak",
  "email": "xxx@gmail.com",
  "latitude": null,
  "longitude": null,
  "phone": null,
  "newsletter": true
}

### HARD DELETE

DELETE localhost:8888/got/v1/users/test/hard

### SOFT DELETE

DELETE localhost:8888/got/v1/users/furczak