@login = user1
@password = password

### LOGIN AS USER

POST localhost:8888/api/v1/auth/login
Content-Type: application/json

{
  "login": "{{login}}",
  "password": "{{password}}"
}

> {% client.global.set("auth-token", response.body.token); %}

### LOGIN AS ADMIN

POST localhost:8888/api/v1/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

> {% client.global.set("auth-token", response.body.token); %}

### GET ALL

GET localhost:8888/api/v1/users
Authorization: Bearer {{auth-token}}

### GET ONE

GET localhost:8888/api/v1/users/{{login}}
Authorization: Bearer {{auth-token}}

### UPDATE

PUT localhost:8888/api/v1/users/{{login}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "name": "bogdan",
  "email": "bogdan@gmail.com",
  "latitude": 12.1,
  "longitude": 21.2,
  "phone": "+48123456789",
  "newsletter": true
}

### HARD DELETE

DELETE localhost:8888/api/v1/users/{{login}}/hard
Authorization: Bearer {{auth-token}}

### SOFT DELETE

DELETE localhost:8888/api/v1/users/{{login}}
Authorization: Bearer {{auth-token}}