### GET ALL

GET localhost:8888/got/v1/users/{{login}}/user-challenges/
Authorization: Bearer {{auth-token}}


### GET COMPLETED

GET localhost:8888/got/v1/users/{{login}}/user-challenges/isFinished
Authorization: Bearer {{auth-token}}


### GET ACTIVE

GET localhost:8888/got/v1/users/{{login}}/user-challenges/isUnfinished
Authorization: Bearer {{auth-token}}


### GET GOALS

GET localhost:8888/got/v1/users/{{login}}/user-challenges/isUnstarted
Authorization: Bearer {{auth-token}}


### ADD NEW

POST localhost:8888/got/v1/users/{{login}}/user-challenges/add-new/{{kgp-challenge-id}}
Authorization: Bearer {{auth-token}}

> {%
    client.global.set("user-challenge-id", response.body.id);
    client.global.set("user-summit4-id", response.body.userSummitList[3].id);
%}

### GET ONE

GET localhost:8888/got/v1/users/{{login}}/user-challenges/{{user-challenge-id}}
Authorization: Bearer {{auth-token}}


### CONQUER

< {%
    request.variables.set("score", "11")
%}

POST localhost:8888/got/v1/users/{{login}}/user-challenges/{{user-challenge-id}}/user-summits/{{user-summit4-id}}/conquer/{{score}}
Authorization: Bearer {{auth-token}}


### UPDATE SCORE

< {%
    request.variables.set("score", "123")
%}

PATCH localhost:8888/got/v1/users/{{login}}/user-challenges/{{user-challenge-id}}/update-score/{{score}}
Authorization: Bearer {{auth-token}}


### DELETE

DELETE localhost:8888/got/v1/users/{{login}}/user-challenges/{{user-challenge-id}}
Authorization: Bearer {{auth-token}}

